# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Informacion', path: 'menu', url: 'about.html'}
- {name: 'Post', path: 'menu', url: 'writing.html'}
- {name: 'Contacto', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/Paolo19010/Miblog'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'instagram', link: 'https://www.instagram.com/paolo_alvarz/'}
- {icon: 'facebook', link: 'https://www.facebook.com/paolo.alvarezvelez/'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Sientete libre de compartir'

related_posts: 'Talvéz te gustaría ver:'

post_date_prefix: 'Escrito en'
